package com.rallygame;

/**
 * This file handles the turns on the roads
 * They have a position on the road, and the distance required to complete the turn.
 *
 * DO NOT EDIT THIS FILE
 */

public class Turn {
    private final int atRoadDistance;
    private int distanceRequired;

    public Turn(final int distance){
        this.atRoadDistance = distance;
        this.distanceRequired = 30;
    }

    public Turn(final int distance, int distanceRequired){
        this.atRoadDistance = distance;
        this.distanceRequired = distanceRequired;
    }

    public void setDistanceRequired(int distanceRequired) {
        this.distanceRequired = distanceRequired;
    }

    public int getDistanceRequired() {
        return distanceRequired;
    }

    public int getAtRoadDistance(){
        return this.atRoadDistance;
    }
}
